language: c++
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt update -qq

install:
  - sudo apt-get -y install qt55-meta-minimal

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - g++ --version
  - make
